#!/bin/bash

# SageMaker passes "serve" as an argument. 
# We ignore it and start our uvicorn server.
# Using 'exec' is important so signals (like SIGTERM) reach the server.
exec /opt/conda/bin/uvicorn server:app --host 0.0.0.0 --port 8080